services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-finance:latest
    ports:
      - "8080:8080"                # host:container
    environment:
      - .env
    restart: unless-stopped