basePath: /api/v1
definitions:
  models.StockPrice:
    properties:
      Trading_Volume:
        type: integer
      Trading_money:
        type: integer
      Trading_turnover:
        type: integer
      close:
        type: number
      date:
        type: string
      max:
        type: number
      min:
        type: number
      open:
        type: number
      spread:
        type: number
      stock_id:
        type: string
    type: object
  models.TaiwanStockPriceResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.StockPrice'
        type: array
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
  title: Go Finance API
  version: "1.0"
paths:
  /finmind/TaiwanStockPrice/{data_id}/{start_date}:
    get:
      parameters:
      - description: stock id
        in: path
        name: data_id
        required: true
        type: string
      - description: start date
        in: path
        name: start_date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TaiwanStockPriceResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Taiwan stock price
swagger: "2.0"
