basePath: /api/v1
definitions:
  models.APIResponse:
    properties:
      data: {}
      error:
        type: string
    type: object
  models.JobStatus:
    properties:
      id:
        type: integer
      name:
        type: string
      next:
        type: string
      prev:
        type: string
      spec:
        type: string
    type: object
  models.JobsAPIResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.JobStatus'
        type: array
      error:
        type: string
    type: object
  models.StockPrice:
    properties:
      Trading_Volume:
        type: integer
      Trading_money:
        type: integer
      Trading_turnover:
        type: integer
      close:
        type: number
      date:
        type: string
      max:
        type: number
      min:
        type: number
      open:
        type: number
      spread:
        type: number
      stock_id:
        type: string
    type: object
  models.TaiwanStockPriceAPIResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.StockPrice'
        type: array
      error:
        type: string
    type: object
info:
  contact: {}
  title: Go Finance API
  version: "1.0"
paths:
  /finmind/TaiwanStockPrice/{data_id}/{start_date}:
    get:
      parameters:
      - description: stock id
        in: path
        name: data_id
        required: true
        type: string
      - description: start date (format YYYY-MM-DD)
        in: path
        name: start_date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TaiwanStockPriceAPIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: Get Taiwan stock price
      tags:
      - Finmind
  /jobs:
    get:
      description: Returns scheduled jobs with next/prev run times and metadata.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JobsAPIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: List scheduled jobs
      tags:
      - Jobs
swagger: "2.0"
